### ISSUE TITLE
Make the web page more css friendly

### ISSUE THREAD

**Issue by MysterDru** [brutaldamage/dual-attack#25]
It might make sense to update the layout of the generated web page to be a little bit more friendly to custom CSS. I think most people will do a similar layout to us, and display the CP, turn & time on the bottom of the camera view, but that might not always be the case.

I'm not sure what make sense for changing the layout. But I'd be open to feedback on if something would make it easier.

**Comment by LargeGeek** [comment]
_This is /u/Bose_Motile btw._

I played with rendering my own HTML and applying some base CSS flex containers to better center and space things. A little customization from here on OBS could go a long way. I ran into origin issues so the script wouldn't update on my local files so I couldn't do a full demo. Maybe provide the 'overlay.html' file along side the index.html to give a better starting point for overlay manipulation.

### overlay.html
```
<html><head>
        <link rel="stylesheet" type="text/css" href="style.css">

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
      </head>
      <body>
        <div class="flex-container">
              <div><span id="leftPlayerCP" class="cpText">0</span></div>
              <div><span id="leftPlayerTime" class="timeText">1:00:00</span></div>
              <div><span id="turn" class="turnText">1A</span></div>
              <div><span id="rightPlayerTime" class="timeText">1:00:00</span></div>
              <div><span id="rightPlayerCP" class="cpText">0</span></div>
        </div>
      <script>
      var hostname = 'window.location.hostname;';
          function keepAlive() {
              var timeout = 500;

              $.getJSON(
                  "http://" + hostname + ":8080/data",
                  function (json) {
                      console.log(json);

                      document.getElementById("turn").innerText = json["score"]["turn"];

                      document.getElementById("leftPlayerTime").innerText = json["timer1"];
                      document.getElementById("rightPlayerTime").innerText = json["timer2"];

                      document.getElementById("leftPlayerCP").innerText = json["score"]["cp1"];
                      document.getElementById("rightPlayerCP").innerText = json["score"]["cp2"];
                  }
              );

              timerId = setTimeout(keepAlive, timeout);
          };
          keepAlive();
      </script>
    
    </body></html>
```
### style.css
```
.flex-container {
  display: flex;
  justify-content: center;
}

.flex-container > div {
  background-color: #f1f1f1;
  width: 100px;
  margin: 10px;
  text-align: center;
  line-height: 75px;
  font-size: 30px;
}
```

**Comment by MysterDru** [comment]
Hey @LargeGeek!  Sweet, this is stellar! I dig this layout & styling way better than what was in here before. 

just for reference in this discussion, this is what the proposed changes above look like:
![image](https://user-images.githubusercontent.com/455639/52155551-03d0e280-2649-11e9-93c5-632f1963ee16.png)

I definitely agree this could go a long way in OBS. It much friendlier for the typical layout of content in the video overlays. 

cc @lanceaeby Thoughts on this layout? Feels like this would be way better to work with given what we're using on Brutal Damage right now.

**Comment by lanceaeby** [comment]
Yes this is much better!  Flex is the way to go.

Thanks @LargeGeek !

**Comment by lanceaeby** [comment]
@LargeGeek , are you cool if I add you as a contributor to our README?  We want to give you credit :)

**Comment by MysterDru** [comment]
merged this into `vNext`. thanks again for the assist @LargeGeek. Should see this change go out in the 1.3.0 release (hopefully later this week)

**Comment by LargeGeek** [comment]
Would be awesome to be listed as a contributor. @LargeGeek is fine. That is my tag everywhere except Reddit.

**Comment by lanceaeby** [comment]
Will do!
